#
# configure promtail to scrape docker logs for a specific
# docker compose project
# https://cylab.be/blog/241/use-loki-to-monitor-the-logs-of-your-docker-
# compose-application
#

server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: kubernetes-pods
    pipeline_stages:
       - cri: {}
       - match:
           selector: '{app="edusec-*"}' # (1)
           stages:
             - json:
                 expressions:
                   log:
             - json: # (2)
                 expressions:
                   sequence: sequence
                   message: message
                   level: level
                   mdc:
                 source: log
             #- json: # (3)
             #    expressions:
             #      traceID: traceID
             #    source: log
             - labels:
                 sequence:
                 level:
             #    personId:
             - output: # (4)
                 source: message
  - job_name: docker
    # use docker.sock to filter containers
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 15s
        filters:
          - name: label
            values: ["com.docker.compose.project=edusec"]
    # use container name to create a loki label
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'