apiVersion: apps/v1
kind: Deployment
metadata:
  name: registro-authorization-server
  labels:
    app: registro-authorization-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registro-authorization-server
  template:
    metadata:
      labels:
        app: registro-authorization-server
    spec:
      serviceAccountName: spring-cloud-kubernetes
      containers:
      - name: registro-authorization-server
        image: urt/registro-authorization-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9091
        env:
        - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
          value: "true"
        - name: SPRING_APPLICATION_NAME
          value: "registro-authorization-server"
        - name: STARTUP_SLEEP
          value: "5"
        - name: SPRING_CLOUD_KUBERNETES_CONFIG_ENABLED
          value: "true"
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLED
          value: "true"
        - name: SPRING_CLOUD_KUBERNETES_CONFIG_ENABLEAPI
          value: "true"
        readinessProbe:
          httpGet:
            path: /management/health/readiness
            port: 9091
            httpHeaders:
                - name: Authorization
                  value: Basic JHt7IHNlY3JldHMuU0VDVVJJVFlfVVNFUl9OQU1FIH19OiR7eyBzZWNyZXRzLlNFQ1VSSVRZX1BBU1NXT1JEIH19
          failureThreshold: 1
          initialDelaySeconds: 30
          periodSeconds: 10
          
        livenessProbe:
          httpGet:
            path: /management/health/liveness
            port: 9091
            httpHeaders:
                - name: Authorization
                  value: Basic JHt7IHNlY3JldHMuU0VDVVJJVFlfVVNFUl9OQU1FIH19OiR7eyBzZWNyZXRzLlNFQ1VSSVRZX1BBU1NXT1JEIH19
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 15
          
---
apiVersion: v1
kind: Service
metadata:
  name: registro-authorization-server
spec:
  ports:
    - port: 80
      targetPort: 9091
      protocol: TCP
  type: LoadBalancer
  selector:
    app: registro-authorization-server