kind: ConfigMap
apiVersion: v1
metadata:
  name: registro-documentos
data:
  application-kubernetes.yml: |-
      registry-documentos:
        logging:
          loki-url: http://host.docker.internal:3100/loki/api/v1/push
      server:
        port: 8096
      spring:
        config:
          activate:
            on-profile: kubernetes
        application:
          name: registro-documentos
        data:
          mongodb:
            uri: mongodb://registrousr:password@host.docker.internal:27017/registrodb
        security:
          oauth2:
            resourceserver:
              jwt:
                issuer-uri: http://host.docker.internal:9091
      management:
        health:
          readinessstate:
            enabled: true
          livenessstate:
            enabled: true
        zipkin:
          tracing:
            endpoint: http://host.docker.internal:9411/api/v2/spans