server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: seg
        uri: http://10.128.0.11:8081/
        predicates:
        - Path=/security/**
      - id: tram
        uri: http://34.72.224.98:9090/
        predicates:
        - Path=/tramAdmon/**
      - id: invoke
        uri: http://34.72.224.98:9090/
        predicates:
        - Path=/invoke/**
      